project:
  type: website
  output-dir: docs

website:
  title: "Football Club 566"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: download.qmd  
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

